### ISSUE TITLE
New CSS Grid

### ISSUE THREAD

**Issue by bravomartin** [processing/processing-website#100]
Hey just so I don't lose the thought...

I was thinking we could move the grid system out of functions and into mixins, [as we did for TIAA](https://github.com/designsystemsinternational/tiaa-pathways/blob/master/src/styles/grid.css), maybe using [this approach](https://every-layout.dev/layouts/sidebar/#the-gutter) instead?

**Comment by runemadsen** [comment]
Closing this in favor of #92
