### ISSUE TITLE
download stuck at donate page

### ISSUE THREAD

**Issue by paddywwoof** [processing/processing-website#118]
I'm using firefox on ubuntu 20.02 I'm technical review for a book on using python and processing which has just been published. I've been asked to do a quick check on some of the software so thought I would download the latest version of Processing. However I don't seem to be able to get past the donate page. Obviously I'm generally happy to donate to things that I use (and pay people money through patreon etc) however you say, almost the first thing on your website, that processing is "free to download and open source." I've downloaded processing several times and don't remember getting stuck like this.

Do you mean that I need to download the source and compile it myself?

Paddy

PS or more likely search on the users forum to find this link https://github.com/processing/processing/releases which will hopefully help others

**Comment by runemadsen** [comment]
Hi @paddywwoof. Thanks for your issue! This repository is for the new processing website, which has not been launched yet. However, when you press "download" on the current website, the software should start downloading and you will then see the donate page afterwards. If you're already seeing the download page, please check your downloads folder. The software should be there.
