### ISSUE TITLE
New book for Books page? (Learn Python Visually)

### ISSUE THREAD

**Issue by tabreturn** [processing/processing-website#141]
https://www.amazon.com/Learn-Python-Visually-Tristan-Bunn/dp/1718500963
https://nostarch.com/Learn-Python-Visually

**Comment by runemadsen** [comment]
Thanks @tabreturn! Would you be up for submitting a pull request with the info? You can see how the other books are created [in this folder](https://github.com/processing/processing-website/tree/master/content/books).

**Comment by tabreturn** [comment]
Done! https://github.com/processing/processing-website/pull/203
Thanks, @runemadsen

**Comment by runemadsen** [comment]
Thank you @tabreturn!
