### ISSUE TITLE
Homepage changes

### ISSUE THREAD

**Issue by runemadsen** [processing/processing-website#146]
- [ ] `sessionStorage` does not work on front page editor
- [x] "See what others are making" links should open in new tab
- [x] Buttons should say “Read Tutorials” and “Go to Reference”
- [x] "Visit the forum" button should open in new tab
- [x] "Teach" in `Navbar` should open in new tab
- [x] Button is partially visible when editor is expanded
- [x] In the “Getting Started” paragraph, the “books” link goes to the Reference and not the books page

**Comment by runemadsen** [comment]
- [ ] `sessionStorage` does not work on front page editor
- [ ] "See what others are making" links should open in new tab
- [ ] Buttons should say “Read Tutorials” and “Go to Reference”
- [ ] "Visit the forum" button should open in new tab
- [ ] "Teach" in `Navbar` should open in new tab

**Comment by bravomartin** [comment]
Fixed everything but the 'sessionStorage'. It works for me, wasn't able to reproduce. 
maybe an old browser? do you have more context?

**Comment by runemadsen** [comment]
Great! I think the `sessionStorage` problem has something to do with the production site, so the code is run during static rendering and never updated to know that there's a `sessionStorage` object.
