### ISSUE TITLE
Reference / String throws a ref error

### ISSUE THREAD

**Issue by bravomartin** [processing/processing-website#166]
It looks like the parsing is generating some keys and it produces two identical keys in this file: 

http://localhost:8000/reference/String.html

<img width="1967" alt="Screen Shot 2021-06-29 at 2 58 07 PM" src="https://user-images.githubusercontent.com/605285/123852657-8ded0600-d8ea-11eb-9d96-5211806de465.png">

**Comment by bravomartin** [comment]
It's actually because the function `length()` is listed twice. the second is a typo. should it be `charAt()` ? not sure where to change it.

![image](https://user-images.githubusercontent.com/605285/123853286-44e98180-d8eb-11eb-957f-6175b055d7d7.png)

**Comment by runemadsen** [comment]
Great catch! Assigning to @Anadroid when she's back. This has to be changed in the Processing source code.

**Comment by Anadroid** [comment]
This is actually a Java reference (meaning it's not in the Processing source code but as a static additional file) which we got by parsing the .xml files so probably something went wrong there, will fix it!

**Comment by bravomartin** [comment]
Same with `getBoolean`. has index twice.

http://localhost:8000/reference/JSONArray_getBoolean_.html
