### ISSUE TITLE
usePreparedExamples paths not working with files on other languages

### ISSUE THREAD

**Issue by ejsandoval** [processing/processing-website#206]
Currently the generated paths for Examples on other languages have this format: `.../es/examples/exampleName.es.html`. This is due to the approach of path construction: 
https://github.com/processing/processing-website/blob/main/src/utils/paths.js#L12
https://github.com/processing/processing-website/blob/main/src/hooks/examples.js#L32-L67. 

We have to make sure the paths don't include the language extension.

**Comment by runemadsen** [comment]
This has been fixes in #255.
