### ISSUE TITLE
Tutorial images are low resolution

### ISSUE THREAD

**Issue by REAS** [processing/processing-website#210]
Many of the images for the tutorials are too low resolution for the new site, they need to be re-created and updated

**Comment by REAS** [comment]
As an update, @digitalcoleman is working through this with my assistance, still a ways to go...

**Comment by runemadsen** [comment]
Great! Let us know if we can assist with anything.

**Comment by runemadsen** [comment]
This seems to be done!

**Comment by REAS** [comment]
half done, but we're actively updating :) fine to close issue

**Comment by runemadsen** [comment]
Ah, sorry! I'll keep it open :)

**Comment by SableRaf** [comment]
Hey @REAS is this still a work in progress? If so which tutorials still need updating?
