### ISSUE TITLE
File IO examples are the wrong size

### ISSUE THREAD

**Issue by REAS** [processing/processing-website#236]
The three examples in the File IO category are 200 x 200 pixels and not 640 x 360 like the others. Adjust these examples to fit the larger size.

**Comment by SanjaySinghRajpoot** [comment]
ok may I work on this issue ?

**Comment by REAS** [comment]
yes, please. if you can, please fork it and then make a pull request. the actual examples are in processing/processing-examples. there's a README in the root of this repo with a link to how to edit examples and i'm here for questions if they come up.

**Comment by SableRaf** [comment]
Reopened this as I realized the .pde files for examples should be edited in the `processing-examples` repository
