### ISSUE TITLE
Broken links in P3D Tutorial

### ISSUE THREAD

**Issue by REAS** [processing/processing-website#240]
Many links within the P3D tutorial are broken. Here's the (as yet) unverified list:
[RGB Cube](http://processing.org/learning/topics/rgbcube.html), [Vertices](http://processing.org/learning/topics/vertices.html), [Toroid](http://processing.org/learning/topics/toroid.html), [Isocahedra](http://processing.org/learning/topics/icosahedra.html) All dead links?
[Example: Texture Quad](http://processing.org/learning/topics/texturequad.html) dead link?
[Texture Triangle](http://processing.org/learning/topics/texturetriangle.html), [Texture Cylinder](http://processing.org/learning/topics/texturecylinder.html), [Texture Cube](http://processing.org/learning/topics/texturecube.html), and [Textured Sphere](https://processing.org/examples/texturesphere.html). Dead Links?
[Textured Sphere](https://processing.org/examples/texturesphere.html) Dead Link?

**Comment by runemadsen** [comment]
Good catch. Are these examples that we need to add to `/examples` and then link to from the tutorial?

**Comment by REAS** [comment]
Yes, but a temp fix could be removing the links, less time than making all of these examples. I can handle this one, but not today :(

**Comment by REAS** [comment]
Another report of broken links here: 

> Hi guys,
> i just discovered your site today,
> amazing
> 
> on this page 
> https://processing.org/tutorials/p3d/#3d-transformations
> 
> this link is broken
> https://processing.org/learning/basics/primitives3d.html
