### ISSUE TITLE
Pd4P3 lib missing from website

### ISSUE THREAD

**Issue by robertesler** [processing/processing-website#246]
I just noticed the new website is missing a reference to my sound library, Pd4P3, here: https://processing.org/reference/libraries/#sound
It is still in the Contribution Manager and was on the old website.  How can I get this corrected? Thank you for your help and time.

**Comment by runemadsen** [comment]
Thanks @robertesler. I'm taking a look at this now!

**Comment by runemadsen** [comment]
Hi @robertesler. This is now fixed and your library should be visible on the website. We are looking at a few problems related to content caching (as explained in https://github.com/processing/processing-website/issues/229) and this might have been the issue. I'll do a real fix for these issues some time next week.

**Comment by prisonerjohn** [comment]
Hi @robertesler your metadata comes from the properties file here: https://www.robertesler.com/software/Pd4P3.txt
You can update this file (and the copy in the library ZIP) and that should be reflected on the website shortly after.
