### ISSUE TITLE
Bug in reading library.properties files on https://processing.org/reference/libraries/

### ISSUE THREAD

**Issue by robertesler** [processing/processing-website#257]
It looks like there is a bug with reading the author line of a library.properties file for posting on the libraries page of the website.  
In the properties file if you write for example:
`authors = First Last` 
The website removes the last character, displaying "First Las" and will hyperlink to a dead address, usually `https://processing.org/reference/libraries/First Las`

I have also tried:
`authorList = [First Last](https://www.validaddress.com)`
and
`authors = [First Last](https://www.validaddress.com)` but they didn't work for me.

This seems to be affecting several libs (BoofProcessing, VSync, Pd4P3 and mouse2DTransformations) and most of the Processing.org libraries (Sound, Video and Hardware) but there may be others I'm not noticing.

**Comment by runemadsen** [comment]
Thanks @robertesler! We'll take a look and report back.
