### ISSUE TITLE
Archived forum gives certification error for all pages

### ISSUE THREAD

**Issue by jeremydouglass** [processing/processing-website#263]
Forum threads and web searches are full of useful references to previous discussions on the archived forums such as http://forum.processing.org/two/

Currently, navigating to any /two/ link gives a certification error. For example:

http://forum.processing.org/two/discussion/14393/getting-the-dominant-color-of-an-image.html

It appears to be a server configuration error -- the HTTP url is auto-forwarded to HTTPS, which then fails.

Solutions:

1. These are historical static pages, with no login and need for https -- just serve as http
2. or, give the archived forum pages a valid certificate

**Comment by jeremydouglass** [comment]
@runemadsen -- very belatedly -- I ran a scan, and all archived forum links are working from the new forum. Thank you so much.

**Comment by runemadsen** [comment]
Great! Thanks @jeremydouglass!
