### ISSUE TITLE
py.processing.org certificate has expired

### ISSUE THREAD

**Issue by tabreturn** [processing/processing-website#265]
@runemadsen -- I'm not sure who manages the server for py.processing.org? The SSL certificate has expired. As a result, Python Mode has disappeared from the Contribution Manager window. Nobody can install it. Of course, the py.processing.org site is down/inaccessible too.

**Comment by zkldi** [comment]
Looks like the certificates for all subdomains have gone down? Having similar issues in #263 and #264.

**Comment by tabreturn** [comment]
Python Mode has reappeared in the Contribution Manager window 😄
