### ISSUE TITLE
Broken Links in P3D Tutorial & 1 typo

### ISSUE THREAD

**Issue by joh-nah** [processing/processing-website#278]
The following hyperlinks from the P3D Tutorial page redirect the user to the "NOT FOUND. You just hit a route that doesn't exist... the sadness" page.

_Primitives 3D_
_RGB Cube_
_Vertices_
_Toroid_
_Isocahedra_ (& typo, should be Icosahedron)
_Example: Texture Quad_
_Texture Triangle_
_Texture Cylinder_
_Texture Cube_
_Textured Sphere_

https://processing.org/tutorials/p3d

@shiffman I watched your 1.4 GitHub Issues video on YouTube and since this is my first filed issue, I figured I'd tag you. How'd I do?

**Comment by shiffman** [comment]
You did great!
