### ISSUE TITLE
2 typos in the P3D tutorial

### ISSUE THREAD

**Issue by MikoYu** [processing/processing-website#279]
For https://processing.org/tutorials/p3d, "Camera" section: 
1. In the first paragraph, there's a missing space between "[...] an upward axis which aligns the camera vertically." and "The default camera position [...]"
2. In the last code block, line 7, there's an extra ">" after the first "mouseX" within the camera().

**Comment by amruth-acharya** [comment]
can i work on this? 😃

**Comment by BabyShark276** [comment]
Sure
