### ISSUE TITLE
Text Tutorials Missing

### ISSUE THREAD

**Issue by glvjr** [processing/processing-website#283]
Hello,

These 2 _Text Tutorials_ are not listed on the new website on the _Tutorials_ page but do have these links to them:

https://processing.org/tutorials/data
https://processing.org/tutorials/trig

Tutorials page:
https://processing.org/tutorials

Reference on forum:
https://discourse.processing.org/t/processing-resources-old-and-new/33045

**Comment by Arya-Gupta** [comment]
I am interested in working on this issue. @SableRaf is this available?

**Comment by SableRaf** [comment]
@REAS was there a reason for leaving the Data and Trig tutorials out? Were they outdated?

**Comment by REAS** [comment]
The Data tutorial was outdated, yes. It used a few web APIs that are no longer live. It was from one of Dan's older books. The Data tutorial could be revived or re-imagined. I had a conversation with Dan about it, so he knows. The Trig tutorial didn't have enough detail and examples in my opinion. It could also be re-imagined, but it wasn't a part of the scope of work when we transitioned the tutorials for the new site.

**Comment by SableRaf** [comment]
Thanks @REAS. I'll close this since those tutorials are "missing" on purpose. If anyone wants to offer a updated/reimagined version of either tutorial, please open a new issue. Thanks!
