### ISSUE TITLE
No diagram in Curves tutorial. 

### ISSUE THREAD

**Issue by tjex** [processing/processing-website#284]
[Curves Processing Tutorial](https://processing.org/tutorials/curves)
In the "Spline Curves" section, it is written that we should refer to two diagrams "at the left", but no diagrams are present. 

> "The tangent to the curve at the start point is parallel to the line between control point one and the end of the curve. These are the lines shown in green in the diagram at the left."

It would be quite useful to see this diagram!

**Comment by SableRaf** [comment]
Thanks for the heads up Tillman :) The diagram will be back in the next release.
