### ISSUE TITLE
Download links broken on https://py.processing.org/tutorials/command-line/

### ISSUE THREAD

**Issue by qozle** [processing/processing-website#297]
Hi, 

I think these download links are broken:

![image](https://user-images.githubusercontent.com/6171907/166153919-6f974917-198d-4b42-bbc9-ecbb2e0c981e.png)

**Comment by SableRaf** [comment]
Hello and thanks for the report! Please note that the Processing.py page has it's own repo and issues page which can be found here: https://github.com/jdf/processing-py-site/issues I will close this issue but feel free to post your report on that repository!
