### ISSUE TITLE
PROCESSING 

### ISSUE THREAD

**Issue by Madtolla** [processing/processing-website#304]
Hello guys
I'm trying to run this code below for 2 days to open the camera by using processing and literally tried every single method but I didn't solve it, plc need your help

import processing.video.*;

Capture video;

void setup()
{
size(550,550);

video = new Capture(this,1080,720,30);
video.start();
}

void draw()
{
video.read();
background(0);
tint(0);
image(video, 0,0);
}
below is the error
"Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help? Troubleshooting."

**Comment by SableRaf** [comment]
Hi @Madtolla. Issues on this repository are only for bug reports and feature requests regarding the Processing website. For help with your project, you can post over on https://discourse.processing.org/ Thanks!
