### ISSUE TITLE
Broken book links in many tutorials

### ISSUE THREAD

**Issue by trikaphundo** [processing/processing-website#308]
The very first paragraph of [the tutorial](https://processing.org/tutorials/coordinatesystemandshapes) points to the book "learning Processing", by Daniel Shiffman, via a hyperlink. That link is broken.

Possible solutions:
1. Link to the [book page](https://processing.org/books/) in the Processing's site, where it is listed along with the rest of books.
2. Link to the website [Learning Processing](http://learningprocessing.com/) directly. It is the book's webpage.

**Edit**: I have looked into all the [text tutorials](https://processing.org/tutorials), and most having a link pointing to a book in the very first paragraph, have that link broken. I paste a complete list of the tutorials with this problem. The solution proposal for these is the same as the previous I wrote up.

- [x] https://processing.org/tutorials/rendering
- [x] https://processing.org/tutorials/video
- [x] https://processing.org/tutorials/print
- [x] https://processing.org/tutorials/network
- [x] https://processing.org/tutorials/electronics
- [x] https://processing.org/tutorials/sound
- [x] https://processing.org/tutorials/2darray
- [x] https://processing.org/tutorials/pixels
- [x] https://processing.org/tutorials/arrays
- [x] https://processing.org/tutorials/text
- [x] https://processing.org/tutorials/objects
- [x] https://processing.org/tutorials/interactivity
- [x] https://processing.org/tutorials/typography
- [x] https://processing.org/tutorials/color
- [x] https://processing.org/tutorials/overview
- [x] https://processing.org/tutorials/coordinatesystemandshapes
- [x] **Edit2**: the [getting started tutorial](https://processing.org/tutorials/gettingstarted) first paragraph's link points to the editorial of the book, instead of the Processing's books page.

**Comment by runemadsen** [comment]
Thanks! We could add id's to each book in the books page in order to deep link to each book.

**Comment by SableRaf** [comment]
That would do it! Thanks @runemadsen

**Comment by trikaphundo** [comment]
> Thanks! We could add id's to each book in the books page in order to deep link to each book.

I think this is the most user-friendly solution.

> That would do it! Thanks @runemadsen

In addition, there is a strange case, which I did not list in my previous comment: the [getting started tutorial](https://processing.org/tutorials/gettingstarted).
The link in the first paragraph is not broken, but points to the editorial of the book, instead of the [Processing's books page](https://processing.org/books).

I was not sure whether this was intentional or not, but now I feel like I should let you know; just in case.

**Comment by runemadsen** [comment]
@SableRaf I just merged #315 which adds the `id` attribute to each book to make it possible to deeplink. Can you take care of updating the tutorial links on your end?

**Comment by SableRaf** [comment]
> @SableRaf I just merged #315 which adds the `id` attribute to each book to make it possible to deeplink. Can you take care of updating the tutorial links on your end?

Nice one! I'll get right to it 😀

**Comment by SableRaf** [comment]
Hey @runemadsen I just tested the anchor links and I found an issue where the OnLoad event triggers the ScrollHandler to scroll back to the top of the page.

**Comment by runemadsen** [comment]
I did wonder about this but it didn't seem to do it on my machine. We'll take a look! If you make a PR with the changes to the tutorial links, I can push the fix to that branch and we can test before merging :)

**Comment by SableRaf** [comment]
Done in https://github.com/processing/processing-website/commit/2a407c81059d146d7c2c27f59ccb6c3f987e82d0

**Comment by runemadsen** [comment]
@SableRaf Can you put some instructions on how to see this on the website? I've clicked through a bunch of tutorial links and they all work perfectly fine as deep links.

**Comment by SableRaf** [comment]
> @SableRaf Can you put some instructions on how to see this on the website? I've clicked through a bunch of tutorial links and they all work perfectly fine as deep links.

I can't seem to reproduce the scrolling bug. It wasn't a major issue anyway so let's move on and we can address it if it comes up again.
