### ISSUE TITLE
Processing and P5js examples not in line with each other

### ISSUE THREAD

**Issue by trikaphundo** [processing/processing-website#320]
There are two example pages in the website, [Scrollbar](https://processing.org/examples/scrollbar.html) and [Handles](https://processing.org/examples/handles.html), whose Processing code shown does not match the changes introduced in this [PR](https://github.com/processing/processing-examples/pull/9) to the processing-examples repository.

My local copy of Processing's website exhibited the very same problem. The [documentation for updating examples or adding examples](https://github.com/processing/processing-website/blob/main/docs/examples.md#updating-examples-via-script) to the website requires

1. A copy of the processing-examples main branch be next to the processing-website repo.
2. From within the root of the processing-website repo, run `npm run updateExamples`

This script will copy the Processing sketches (.pde files) from processing-examples to their corresponding locations in processing-website; it will actually only update those that already exist in the processing-website repo.
I did this in my computer and the problem is solved: the .pde code shown in the Handles and Scrollbar example pages is the same as the .pde code in the processing-examples repo.

**Comment by SableRaf** [comment]
Thanks for the heads up! I updated these two as well as a bunch of other examples that were lagging behind. See the commit above for the full list.

Note: Please ignore the mention above (321). It was added by mistake.
