### ISSUE TITLE
Update menu items on the Documentation > Environment page

### ISSUE THREAD

**Issue by SableRaf** [processing/processing-website#328]
Menu items on the Environment page (https://processing.org/environment/) need to be updated to match the Processing 4 menus

**Comment by Arya-Gupta** [comment]
Hey @SableRaf, I am interested in working on this issue. Could you elaborate it a bit more?

**Comment by SableRaf** [comment]
Hi @Arya-Gupta and thanks for your offer to help ✨

There is a mismatch between the description of the menus in the reference page and the actual order of the menus in the software. Some items that were added recently are also missing. For instance, the Help section is missing "Welcome to Processing" and "Download Offline Reference". The Environment (IDE) reference page needs to be updated to match the menus in the PDE.

Information on how to edit markdown pages on the Processing website can be found here: https://github.com/processing/processing-website/blob/main/docs/markdown-pages.md

I hope this helps. Let me know if there is anything else I can clarify.

**Comment by Arya-Gupta** [comment]
@SableRaf what kind of description should I add for the new items in the menus such as the ones you mentioned above?

**Comment by SableRaf** [comment]
@Arya-Gupta feel free to make suggestions and we can work from there :)
