### ISSUE TITLE
curveDetail example uses default renderer

### ISSUE THREAD

**Issue by clankill3r** [processing/processing-website#334]
https://processing.org/reference/curveDetail_.html

This is the example for curveDetail:

<img width="307" alt="Screenshot 2022-09-19 at 11 56 20" src="https://user-images.githubusercontent.com/738650/190993721-7f8300c4-287e-4ee2-ad89-d49fe79fd409.png">

The thing is, the example should not use the default renderer cause curveDetail does not work there.
This is what it looks like when switching to P2D (as intended):

<img width="512" alt="Screenshot 2022-09-19 at 11 56 54" src="https://user-images.githubusercontent.com/738650/190993909-fc39c2fa-ee04-4440-910e-629f261fe983.png">

Also it makes more sense to have all draw code in setup, cause now the first curve will become white after the first frame, and the become all ugly from drawing on top of each other.

**Comment by SableRaf** [comment]
Hi Doeke you're absolutely correct! If you want to make a pull request for this I will happily merge it.

The following code works as intended:

```JavaScript
void setup(){
  size(400,400,P2D);
}

void draw(){
  curveDetail(1);
  drawCurves(-60);
  stroke(126);
  curveDetail(2);
  drawCurves(0);
  stroke(255);
  curveDetail(4);
  drawCurves(60);
  noLoop();
}

void drawCurves(float y) {
  noFill();
  curve( 20, 112+y,  20, 112+y, 292, 104+y, 292, 252+y);
  curve( 20, 112+y, 292, 104+y, 292, 252+y, 60, 268+y); 
  curve(292, 104+y, 292, 252+y, 60, 268+y, 60, 268+y);
}
```

**Comment by SableRaf** [comment]
Hi @yogitheboss. Thanks for your help ✨ I have assigned the issue to you. You will find information on how to update examples in the reference in [`reference.md`](https://github.com/processing/processing-website/blob/main/docs/reference.md). Let me know if you have any questions.
