### ISSUE TITLE
Add Happy Coding to the Learn>Tutorials page

### ISSUE THREAD

**Issue by tokidokiknitter** [processing/processing-website#339]
Would love to see the [Happy Coding](https://happycoding.io/) site added to the LEARN / TUTORIALS page. Its breadth, depth, and organization of information for people new to coding/programming are excellent.

**Comment by SableRaf** [comment]
Thanks for the suggestion @tokidokiknitter! 

https://happycoding.io/tutorials/processing/ will be added to the tutorials selection in the next website release
