### ISSUE TITLE
One possible clerical error is in tutorials/text/color

### ISSUE THREAD

**Issue by HairlessVillager** [processing/processing-website#348]
https://github.com/processing/processing-website/blob/c16d62f30b582057b899a20534658dc7fb97c87f/content/tutorials/text/color/index.mdx?plain=1#L133

```cpp
// 255 means 100% opacity.
fill(255,0,0,255);
rect(0,0,200,40);
// 75% opacity.
fill(255,0,0,191);
rect(0,50,200,40);
// 55% opacity.
fill(255,0,0,127);
rect(0,100,200,40);
// 25% opacity.
fill(255,0,0,63);
rect(0,150,200,40);
```

suggest: `55%` -> `50%`

**Comment by SableRaf** [comment]
@Raghav-Programmer The issue is that `fill(255,0,0,127)` corresponds to roughly `50%` opacity, not `55%`.

**Comment by Raghav-Programmer** [comment]
change 127 to 140.25 for 55% opacity

**Comment by HairlessVillager** [comment]
> what exactly is the issue??

very sorry for the misunderstanding, but I thought maybe less is more¯\_(ツ)_/¯ sorry again

**Comment by Raghav-Programmer** [comment]
So the issue is resolved or you didn't want 55%??

**Comment by HairlessVillager** [comment]
@Raghav-Programmer It seems that you are worrying about your first contribution. However, it doesn't matter if you just offered help. Take it easy~ 🥰

**If you still want to contribute, you can see [About pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests). Then fix this bug and commit your pr. Just try it! **😃

I will close this issue and check the bug later. I really hope you can commit your pr and learn from it. But if you can't, I will. 👌
