### ISSUE TITLE
404 on local Language Reference "back to cover" image

### ISSUE THREAD

**Issue by Loud-Cat** [processing/processing-website#349]
### Issue description
In the Language Reference local website (found via Help -> Reference in the Processing IDE), there is an image with the text "Processing" and title "Back to the Processing cover." Upon clicking the image, instead of being sent to the "cover" web page (`http://localhost:8053/reference/index.html`), I get sent to a page that says "404 Not Found" (`http://localhost:8053`)

![image](https://user-images.githubusercontent.com/73842360/209584114-3f37f4c7-f5e5-4518-aaea-048676c9404e.png)
![image](https://user-images.githubusercontent.com/73842360/209584173-c0dfb4fe-4012-4e08-884a-e394c1509620.png)

### URL(s) of affected page(s)
`http://localhost:8053/reference/index.html` (and all other pages of the language reference)

### Proposed fix
In the source code, change the `href` property of the anchor tag (`<a>`) under `#header` (`<div id="header">`) from `"/"` to `"/reference/index.html"`

**Comment by SableRaf** [comment]
The local reference has been updated along with the new website. Make sure to use the latest version of Processing, download the local reference, and you should be good to go! Thanks for your feedback :)
