### ISSUE TITLE
`raw.github.com` does not redirect to `raw.githubusercontent.com` for me

### ISSUE THREAD

**Issue by JobLeonard** [processing/processing-website#355]
### Issue description

`raw.github.com` does not always redirect to `raw.githubusercontent.com`, resulting in dead links for some users.

> In order to better isolate your content from potentially malicious content uploaded by other users (e.g., content that might contain Cross-Site Scripting or other embedded attacks), we now serve user-generated content from subdomains of githubusercontent.com. This content is no longer served from subdomains of github.com.
> 
> ##What's affected?
>
> This change affects the following subdomains:
> 
> - `raw.github.com` : Serves raw file content from your repository.
> - `embed.github.com` : Allows users to embed rich GitHub content on other sites.
> - `render.github.com` : Displays rich content on GitHub.com.
> - `f.cloud.github.com` : Hosts all those amazing gifs you use in Pull Requests and Issues.
>
> Content formerly served by these subdomains is now served from subdomains of `githubusercontent.com`.

https://developer.github.com/changes/2014-04-25-user-content-security/

(was first raised here: https://github.com/processing/processing/issues/4947#issuecomment-284753326 )

### URL(s) of affected page(s)

https://raw.github.com/processing/processing/master/build/shared/revisions.txt as linked from https://processing.org/download/?processing

### Proposed fix

Replace affected links with `githubusercontent` domain, i.e. https://raw.githubusercontent.com/processing/processing/master/build/shared/revisions.txt

**Comment by RohanGd** [comment]
Exactly, it says page not found, any help would be highly appreciated
<img width="956" alt="image" src="https://github.com/processing/processing-website/assets/90324169/c0f7978f-a57a-40ab-b3d7-a5a7057de5c3">

**Comment by SableRaf** [comment]
@RohanGd judging by your screenshot it looks like your issue is related to NLTK. This repository is for the Processing website. It is not related to- or maintained by- the NLTK team. You may want to report your issue at https://github.com/nltk/nltk
