### ISSUE TITLE
facing issue while setting up dev environment

### ISSUE THREAD

**Issue by aditya-shrivastavv** [processing/processing-website#419]
First I ran `npm install` after that all the modules were downloaded. but when i ran `npm run dev` this error poped up. 

![Screenshot_20230127_061251](https://user-images.githubusercontent.com/81470938/215091134-f8ac9e08-5bbd-4869-9ea0-fe471e745398.png)

**Comment by Dev-Code24** [comment]
try deleting the node modules and do "npm i" again and then run the code "npm run dev"
