### ISSUE TITLE
Social media links do not open in new page

### ISSUE THREAD

**Issue by Arya-Gupta** [processing/processing-website#424]
The footer of the [processing website](https://processing.org/) contains social media links to Twitter, Medium, Instagram, and GitHub. On being clicked, these do not open in a new tab. This might be annoying for a user who wants to open multiple links.

How to replicate:
- Visit the [processing website](https://processing.org/)
- Click any of the social media links in the footer

![image](https://user-images.githubusercontent.com/84087089/215467890-4f78c3a0-f005-4243-b60d-c902c74613d7.png)

**Comment by Arya-Gupta** [comment]
I am interested in working on this issue. Can I be assigned?

**Comment by SableRaf** [comment]
Thanks @Arya-Gupta. You got it!

**Comment by Dev-Code24** [comment]
<img width="870" alt="image" src="https://user-images.githubusercontent.com/97425135/216039767-e4390250-fee1-43e7-b5c5-2f740d82053c.png">

here alsi when the button is clicked the link does not open on a new tab
