### ISSUE TITLE
Screen reader friendly top-bar links

### ISSUE THREAD

**Issue by SableRaf** [processing/processing-website#425]
Lighthouse has identified that the links in the top bar on the Processing website do not have discernible, unique, and focusable link text.

Fixing this will make the website more accessible to users who rely on screen readers to navigate the web.

### Proposed solution
Adding [`<title>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title) and [`<desc>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/desc) elements to the SVGs.

Source: https://stackoverflow.com/a/62831018/2126791

### Lighthouse report
Here is a screenshot of the Lighthouse report:

![image](https://user-images.githubusercontent.com/290261/216039174-9679727c-6621-4088-a69b-9190195a0bd2.png)

**Comment by kushalnl7** [comment]
Hello @SableRaf , can you please assign this to me?

**Comment by SableRaf** [comment]
Sure @kushalnl7! Thanks for your contribution :)

**Comment by kushalnl7** [comment]
I have raise a PR - #429 for this issue. Please review it.

**Comment by SableRaf** [comment]
Thanks @kushalnl7 ✨ While reviewing your PR, I found there is a span element with `Topbar-module--name--4+Tmy` class that does get picked up by screen readers so the `title` element is redundant. Very sorry for that!

My tests also showed that the dropdown menus are not fully optimized for screen readers so this was still useful! I will create a new issue regarding the dropdowns and maybe you'll be interested to look into that? Thanks again for your efforts!
