### ISSUE TITLE
"Hello Processing!" tutorial has stopped working on contemporary browsers

### ISSUE THREAD

**Issue by paraclete-pizza** [processing/processing-website#437]
I use the "Hello Processing!" tutorial as an accessible introduction to creative code with lots of my students (even if we end up doing actual work in P5 more now).

This year, my students and I noticed that the synchronized components of the tutorial don't work in Chrome, Firefox, or Edge any more. At the point where Dan exclaims that he's popping into the corner and the edit window should pop up, neither happens, which means the tutorial is no longer interactive.

Since the tutorial is still the first thing listed under the "Learn" section of the website, I assume it's not deprecated. If it is, maybe it should be removed form the site (though I'd prefer the tutorial be updated to work in contemporary browsers if possible- it's still stellar, and at the very least deserves to be accessible for posterity).

**Comment by SableRaf** [comment]
Hello @paraclete-pizza and thanks for your report! Could you say more about how this issue manifests for you? 

I have been going through the tutorial and making small fixes to the video embeds recently, and I didn't notice any issue with interactive components in Chrome on my end.

This is what I see in the latest version of Chrome:

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/290261/218466663-c7a1682b-9e0a-46aa-be96-a13af8097ddd.png">

**Comment by paraclete-pizza** [comment]
It looks like it's working for me now!
When I was following up on my students' queries on Friday, multiple elements weren't working in any browser. Specifically, the timeline at the bottom of the screen didn't display progress, the four control buttons ("Caption" - "Jump to Exercise") were non-responsive, and the moment in "Shapes" when we were supposed to shift to a small video with interactive code windows didn't work - the video just kept playing full screen.

I'm so glad that it's working now, though it's a bit late for my uses - I just had to coble together an alternative 'reading assignment' out of some of Shiffman's P5 videos, which still worked, but wasn't nearly as elegant as this wonderful tool!

**Comment by SableRaf** [comment]
Ok too bad we couldn't replicate this. It would be interesting to know what caused the issue in the first place. If you come across this again, please open a new issue and share the Operating System, browser version, and any errors that appear in the JavaScript console. Thanks for your help!
