### ISSUE TITLE
Incorrect link in PFont reference

### ISSUE THREAD

**Issue by glvjr** [processing/processing-website#468]
This page has a link that is incorrect:
https://processing.org/reference/PFont.html

The incorrect link is at the bottom of the page in the related section:
[PGraphics::textFont()](https://processing.org/reference/PGraphics_textFont_.html)

The link should be:
https://processing.org/reference/textFont_.html

``:)``

**Comment by Stefterv** [comment]
https://github.com/processing/processing-website/pull/469#issuecomment-1674353095 Not fixable in this repository
