### ISSUE TITLE
Missing hover state for external links

### ISSUE THREAD

**Issue by harshsharma-11** [processing/processing-website#479]
https://github.com/processing/processing-website/assets/138685168/35e553f6-61b4-451d-b401-8653c7f2ce0e

**Comment by harshsharma-11** [comment]
@limzykenneth please review

**Comment by SableRaf** [comment]
Hi @harshsharma-11,

Thanks for submitting an issue on the Processing website repo. Videos can be useful, but a written description helps us understand and fix the issue faster. Could you please add more text details to your issue?

Also, please avoid tagging random people for review in the future. I have removed those mentions. We will make sure the right person sees the issue. Thank you.

**Comment by harshsharma-11** [comment]
> Hi @harshsharma-11,
> 
> Thanks for submitting an issue on the Processing website repo. Videos can be useful, but a written description helps us understand and fix the issue faster. Could you please add more text details to your issue?
> 
> Also, please avoid tagging random people for review in the future. I have removed those mentions. We will make sure the right person sees the issue. Thank you.

sir how can i know who is the maintainer of particular repo ,please can you provide how i find people maintaining the particular repo of processing so i can tag the right one

**Comment by harshsharma-11** [comment]
sorry for that ,i want to point that the links the footer can have hover effect ,whether changing the background of links or color of links on hovering

**Comment by harshsharma-11** [comment]
something like this 

https://github.com/processing/processing-website/assets/138685168/8da3d4a5-e3e6-419a-8eae-c47148344d1f

**Comment by siddanth-6365** [comment]
can i pick this issuse?

**Comment by Afrin127329** [comment]
> home._.p5.js.-.Google.Chrome.2023-10-05.17-34-42.mp4

@harshsharma-11 This is the repo from processing.org website, not ps5.js.
