### ISSUE TITLE
[Feat]: Add Social Media Logo to footer navigation links

### ISSUE THREAD

**Issue by umangutkarsh** [processing/processing-website#483]
**Is the feature request related to a problem? Please describe.**
Logo in social media links

**Describe the solution**
The social media navigating links in the footer should have a Logo. For  better UI experience.

**Additional context**
![footer](https://github.com/processing/processing-website/assets/95426993/4fb496ec-77fa-43bb-9725-297a1c3ef0f1)

**Acceptance Criteria**

- [X] Twitter logo
- [X] Medium logo
- [X] Instagram logo
- [X] Github logo

**Comment by umangutkarsh** [comment]
Hi @SableRaf . I've raised an issue for a feature request. Please let me know if it's good for implementing. 
I've also created a PR for this. Please review it and provide your feedback on it.
Thanks for your time.

**Comment by Stefterv** [comment]
<img width="1770" alt="Screenshot 2024-07-26 at 13 47 15" src="https://github.com/user-attachments/assets/b58c245c-de59-4cf0-8abb-772f99dd7307">
<img width="1770" alt="Screenshot 2024-07-26 at 13 47 17" src="https://github.com/user-attachments/assets/f57c6deb-85fd-4ded-bcb1-8d1bf7c3d957">

Hi umangutkarsh,

Thank you for your contribution! We like to keep the home page devoid of logos and branding from third party companies.

@SableRaf Feel free to reopen if you decide differently
