### ISSUE TITLE
Text not visible properly

### ISSUE THREAD

**Issue by gunjjoshi** [processing/processing-website#489]
![image](https://github.com/processing/processing-website/assets/67432819/9f6efee6-ee26-45a6-bd96-6f3e0b49f68a)

The character "S" of text "Search" inside the search bar is not visible completely. It is cut from above.
Can you please assign me this issue for quick rectification ?

**Comment by micuat** [comment]
Thank you for the issue and PR. What environment (OS/browser) are you using? I don't see this issue on macOS 13.2.1 on firefox/chrome/safari.

**Comment by gunjjoshi** [comment]
I am using Windows 10, Microsoft Edge web browser.

**Comment by gunjjoshi** [comment]
When I zoom in, it becomes fine.
![zoomin](https://github.com/processing/processing-website/assets/67432819/60fbd882-7808-494c-8183-e00faa2861e0)

But, on zooming out, it cuts again.
![zoomout](https://github.com/processing/processing-website/assets/67432819/4d2298ee-8ec3-46e5-b48a-4606e25f09a4)

**Comment by Afrin127329** [comment]
@SableRaf Padding could be increased for better visibility of the searchbar.

**Comment by gunjjoshi** [comment]
It is already done in the merged PR. Would be better if you refer that.
