### ISSUE TITLE
Incorrect link in forum

### ISSUE THREAD

**Issue by glvjr** [processing/processing-website#490]
A link in this topic needs to be corrected:
[https://discourse.processing.org/t/welcome-to-the-processing-foundation-discourse/8](https://discourse.processing.org/t/welcome-to-the-processing-foundation-discourse/8)

This link (in content of above page) directs to the last topic 4:
[https://discourse.processing.org/t/guidelines-asking-questions/2147/4](https://discourse.processing.org/t/guidelines-asking-questions/2147/4)   _**Remove the /4**_

It should point to the first topic:
[https://discourse.processing.org/t/guidelines-asking-questions/2147](https://discourse.processing.org/t/guidelines-asking-questions/2147)

******************************

The pinned link here (when you log in there is only one):
[https://discourse.processing.org/](https://discourse.processing.org/)

Change from:
[https://discourse.processing.org/t/welcome-to-the-processing-foundation-discourse/8/2](https://discourse.processing.org/t/welcome-to-the-processing-foundation-discourse/8/2)  **_Remove the /2_**

To:
[https://discourse.processing.org/t/welcome-to-the-processing-foundation-discourse/8](https://discourse.processing.org/t/welcome-to-the-processing-foundation-discourse/8)

**Comment by AdityyaX** [comment]
Hi @glvjr ,
I hope you're doing well.
Could you kindly provide additional context or clarify some points regarding this issue?

**Comment by glvjr** [comment]
Hello,
The links should go directly to the top of the topics.
I have edited the above post for clarity.

**Comment by Avadhut20** [comment]
Hi @glvjr, I want to work on this issue can you please assign it to me?

**Comment by SableRaf** [comment]
Thanks @glvjr. I have fixed the links on the forum.
