### ISSUE TITLE
cutting placeholder text because of width.

### ISSUE THREAD

**Issue by iadarshrawat** [processing/processing-website#492]
![Screenshot 2023-11-11 235515](https://github.com/processing/processing-website/assets/121751042/557e3edc-78bf-4a1b-8193-042d9eaaaf74)
text inside the search-box (placeholder) is cutting because of less width. When we zoomed it, it seem properly but when we zoomed out, problem is created.

**Comment by rsharvesh16** [comment]
@iadarshrawat  #491 Resolved the issue.

**Comment by iadarshrawat** [comment]
Okk @rsharvesh16. I will close this issue right now.
