### ISSUE TITLE
Feat: There should be a back to Home button or automatic redirection feature on 404 Not found page for better user experience

### ISSUE THREAD

**Issue by Afrin127329** [processing/processing-website#498]
Right Now if we visit any 404 page, it just shows the below texts only. It would be great if there was a back to home button or a feature like after 3 seconds of visiting a 404 page, user will be automatically redirected to home page of the website. @SableRaf Could you please confirm it?

![image](https://github.com/processing/processing-website/assets/125039325/5fdc3cbc-9692-432b-98d8-6afd646b0ff3)

**Comment by UzairDevs** [comment]
Can we start working on this or should we wait for the maintainer to confirm it?

**Comment by Afrin127329** [comment]
@UzairDevs I think it would be better to wait for the approval from maintainers.

**Comment by praveen-rikhari** [comment]
@Afrin127329 @UzairDevs Are you guys working on it? If not, can i take this issue?

**Comment by Afrin127329** [comment]
@praveen-rikhari Not working on it for now. You can pick if you want to. Thanks

**Comment by praveen-rikhari** [comment]
Thanks @Afrin127329 Surely I will work on it.

**Comment by praveen-rikhari** [comment]
Thanks @SableRaf for assigning this task. 
Do I also need to add some styling on the page?

**Comment by Stefterv** [comment]
Moving to Netlify has fixed this issue seemingly
