### ISSUE TITLE
Addressing Inconsistent Button Animation Colors

### ISSUE THREAD

**Issue by AdityyaX** [processing/processing-website#499]
### Description:
The button animation feature currently displays inconsistent colors This inconsistency undermines the intended design and user experience, leading to a lack of uniformity in the visual presentation of the interface.

### Steps to Reproduce:
1. Open the application on different devices (desktop, mobile, tablet).
2. Navigate to the section with button animations.
3. Observe the colors displayed during the animation.

### Expected Behavior:
The button animation colors should remain consistent across all devices and browsers to ensure a cohesive visual experience for users.

### Actual Behavior:
The colors displayed during button animations vary, presenting different shades or hues on different devices and browsers.

https://github.com/processing/processing-website/assets/103623274/d9c52448-1d86-4a98-9ee6-39abba04d3cb

### Proposed Solution:
1. Conduct a thorough review of the current color implementation for button animations.
2. Ensure compatibility and consistency across various devices and browsers.
3. Implement a standardized color scheme or utilize CSS variables to maintain consistency.

### Environment Details:
- **Device:** MacBook Air
- **Browsers:** Chrome

**Comment by riyanrathore26** [comment]
@SableRaf i want to work on this issu please assignee me.
also also share what type of animation do you want

**Comment by Stefterv** [comment]
@SableRaf I think the UX here works okay already, any visual indicators of a difference in UX behaviour doesn't work graphically.

**Comment by SableRaf** [comment]
Agreed. I appreciate the thoughtfulness of the proposed change but I think the current design is functional.
