### ISSUE TITLE
Placeholder Text Issue in Search Input

### ISSUE THREAD

**Issue by Swarnendu0123** [processing/processing-website#502]
## Steps to Reproduce:

1. Visit the [Processing website](https://processing.org/).
2. Locate the search bar in the navigation.
3. Observe the placeholder text before and after clicking on the search input box.

## Expected Behavior:
The placeholder text should remain as 'Search with Google' both before and after clicking on the search input box.

## Actual Behavior:
Initially, the placeholder text is 'Search,' but when clicking on the input box, it changes to 'Search with Google.'

## Video Attachment:
https://github.com/processing/processing-website/assets/94161758/cd74fc6f-8717-4878-8810-2cd1700cba94

**Comment by macayu17** [comment]
I would like to contribute to this issue!

**Comment by Shitanshu731** [comment]
I am keen on getting involved and contributing to this issue!
