### ISSUE TITLE
bug : Placeholder in searchbar in home page 

### ISSUE THREAD

**Issue by shubhamshinde01** [processing/processing-website#509]
### steps to reproduce :
 <hr>

1. Visit the [Processing website](https://processing.org/).

2. Locate the search bar in the navigation.

3. Observe the placeholder text before and after clicking on the search input box.

### Actual Behavior :
<hr>
Initially, the placeholder text is 'Search,' but when clicking on the input box, it changes to 'Search with Google.'

###  Expected Behavior :
<hr>
The placeholder text should remain as 'Search with Google' both before and after clicking on the search input box.

### Video Attachment :
<hr>

https://github.com/processing/processing-website/assets/93381750/852df1be-f3dd-4be7-84fb-9ebb8aaab502

**Comment by SableRaf** [comment]
Thank you for the suggestion. I'd prefer not having "Google" in the header at all times.  One alternative I would support is changing the text to "Search (via Google)" when the input box is focused. This would make the interaction flow a little clearer.
