### ISSUE TITLE
Docs error on textureMode

### ISSUE THREAD

**Issue by huadmin** [processing/processing-website#527]
Please note the error in the code examples on this page:

https://processing.org/reference/textureMode_.html

The text indicates that IMAGE is the default mode, yet in the two code exx., the one with the normalized coordinates omits the texturemode command entirely (which is the point of the doc page: to show the command in use; this code will not run as intended and will instead show one pixel of the source expanded to the size of the Shape) and the one with Image pixel coordinates redundantly includes texturemode, when I am sure the writer meant to do the reverse.

**Comment by SableRaf** [comment]
Hi @huadmin and thanks for reporting this issue! You're absolutely correct. This should be a quick fix.
