### ISSUE TITLE
Selection of font "Space Mono" for code display is not ideal

### ISSUE THREAD

**Issue by pzelchenko** [processing/processing-website#528]
![image](https://github.com/processing/processing-website/assets/7409590/9a2e5128-5ad5-4fa8-bc91-a00b86074e41)

On the Processing.org website ([example](https://processing.org/examples/graphing2dequation.html)), I have to take exception on the use of Colophon's "[Space Mono](https://fonts.google.com/specimen/Space+Mono)" for code. Code doesn't parse like regular text. The absence of any hook on the minuscule "j" in the style used makes it read like an "i". "i" and "j" are the most common names for iterating-variables for nested loops, and [that's been the case](https://stackoverflow.com/questions/4137785/why-are-variables-i-and-j-used-for-counters) since your grandfathers' time ("i" stood for "integer" or maybe "iterate" and then you'd use i, j, k, etc.). I can't for the life of me imagine why the CSS selects OpenType [stylistic set "ss02"](https://sparanoid.com/lab/opentype-features/), which features that truncated "j". Perhaps even more troubling is that the comma and period are very difficult to distinguish at the default size (14px), and naturally that's a fatal problem for reading code. Please find a suitable solution. This issue costs me and my students time basically every day. Removing "ss02" only resolves the "j" problem, but you're still left with the comma/period conundrum (I'm not sure what the use of "ss04" and "ss05" have in store for the user, but it's also worth investigating).

So, you may want to choose a different font or let Colophon help you revise the font or find some other solution. If you want me to be involved in figuring out an appropriate solution, let me know. I've already sent basically the same report to [Design Systems International](https://designsystems.international/), since they [appear to have been involved at one point](https://processing.org/people/), but I don't know who makes font decisions now.

https://processing.org/examples/graphing2dequation.html

**Comment by pzelchenko** [comment]
I'd add that colon and semicolon are also problematic, see above. More relevant with Python code than Java/C dialects, but still it's distracting. Anything else?

**Comment by pzelchenko** [comment]
The curly brace is also too understated, at least at 14px. The distinctions from its cousins, the parentheses and square brackets, begin to fade.

**Comment by SableRaf** [comment]
Hi @pzelchenko and thanks for your detailed analysis of the font choice for our code snippets. I trained as a type designer too and though I haven't been active in the field for over a decade I remember enough to be very sensitive to your arguments :)

Which monospace typefaces would you suggest as suitable replacements? My personal go to for its simplicity and legibility has been JetBrains Mono. It's free and Open Source which would make it a good fit. I'm open to other suggestions though.

**Comment by TechnicJelle** [comment]
I've been a big fan of JetBrains Mono ever since it released for the same reason: unparalleled legibility.
So a +1 for JetBrains Mono from me :)

**Comment by pzelchenko** [comment]
Hello Raphaël @SableRaf and @TechnicJelle, thanks so much for responding. Sorry this took so long.

I reached out to Edd and Gena at Colophon and they don't seem to have any interest in getting on board for modifying. That's not a great tragedy, because I took a closer look at the font and I feel it is somewhat beyond the design's ability to discuss even emergency rescue measures. I'm not even going to bother digging into the maw of my Google contacts.

I haven't used JetBrains for work. If you like it, maybe it can work. However, I also think Adobe Source Code Pro is well worth looking at. Perhaps there are others, but in the interest of efficiency I'd advise against getting carried away with more comprehensive comparisons. I put a test together for comparison and discussion:

[Test Space Mono Regular, JetBrains Mono, Source Code Pro](http://pete.zelchenko.com/2024/processing_fonts/)

Here are criteria that I consider relevant for good monospace code fonts. Perhaps you can add some others:
- i, j differentiation
- comma, period and semicolon, colon differentiation (sufficiently long tail on the comma at small sizes to distinguish)
- 0 and O, 1 and l
- no clogging (within-glyph component-crowding) in critical glyphs at small sizes e.g. * 0 % $
- escapement (between-glyph) rationally based but visually reasonable and no sense of crowding or encroachment e.g. oio
- bracket () [] {} glyph widths should all be consistent and warranted, without crowding of contained or external matter
- where biform (sans + serif mixed), should be warranted e.g. i l 1
- stems of CL-symmetric glyphs e.g. + * not lopsided at small sizes (left-right, top-bottom)
- generous, consistent widths of basic math operators e.g. + - = (but not crowding, even if space omitted)
- overall visual coherence and aesthetic considerations

One thing I noticed is the vast file size payload difference, with JetBrains being the largest by far. However, I don't think this should be as important a factor as legibility. My first thought about JetBrains is that it looks reasonably clear, but perhaps unnecessarily vertical.

![image](https://github.com/processing/processing-website/assets/7409590/0fb93024-5032-435e-87e1-71cd0f40850e)

**Comment by TechnicJelle** [comment]
If you look at the [JetBrains Mono site](https://www.jetbrains.com/lp/mono/), it demonstrates its specific focus on increased legibility regarding most of your criteria.

Regarding the file size, the font could be tree-shaken, which means that all unused characters are removed from the font.

**Comment by TechnicJelle** [comment]
Yes, I also very much enjoy the JetBrains Mono site.
It does an excellent job at showing off its features and qualities. And also the reasons behind the choices they made. Because some things definitely aren't standard. But they work exceptionally well!

I regularly go there just to look. It's like going to the museum to look at your favourite painting, haha.

**Comment by pzelchenko** [comment]
Well, it looks like at least 3 people trust JetBrains Mono. So what's the next step? Should we run a survey, or just throw it out there and see?

**Comment by SableRaf** [comment]
@TechnicJelle Thanks for https://www.codingfont.com/ it was fun to go through. I got JetBrains Mono! Though I'm not sure we can really say that I wasn't "influenced by prior knowledge" 😄 Regarding the file size, [JetBrainsMono-Regular.ttf](https://github.com/JetBrains/JetBrainsMono/blob/master/fonts/ttf/JetBrainsMono-Regular.ttf) is 268Kb. What would be the size after tree shaking unused glyphs?

@pzelchenko Thanks for the detailed feedback and for making the sample page! 

I'd say we can go for **JetBrains Mono** since all three of us seem to agree that it's a good choice. Would either of you be willing and able to make a pull request for this change? Otherwise I will look into it but it may take a little while before I find the time.

**Comment by pzelchenko** [comment]
Hi, guys, thanks for the feedback. Aside from some perhaps minor concerns, JetBrains is excellent. I have to say that after seeing Input Mono, I feel that JetBrains has some strong competition. Input Mono is one of the cleanest, clearest code fonts I've seen. No obvious idiosyncrasies to explain. And it has the same x-height advantage JetBrains claims. I feel that it could edge out JetBrains on many of the metrics I sketched out above.

There's another thing worth considering, and that is that Input Mono is part of a full family, including many weights of serif and sans proportional fonts. Presumably, Space was originally selected as the family for the website because it had a matching Mono. Simply switching out the code font raises congruity questions. While that's minor to me (I shed my puerile purism about type a long time ago), it's an issue for such a well-designed website. Somebody put a lot of effort into the site design here.

That said, looking closely at Input Mono, despite an (exhaustive!) set of weights, clearly it was designed for coding and not for text. Even its proportional sans can't compare visually to Space Grotesk:

![image](https://github.com/processing/processing-website/assets/7409590/ef284bdc-0078-426f-8c52-e439eee274c8)
![image](https://github.com/processing/processing-website/assets/7409590/83cbe4bb-a37d-40c5-87aa-4bc4ac9e5eda)

No contest. Space Grotesk is a pretty sweet font. Still, it's a (minor) added point to consider for the future, how the code font and the text font work together visually. I've asked David Ross, who designed Input, if he has any knowledge of a good-looking general web text font that complements Input Mono. Just for future reference, since I think it'd be a longshot to expect to change the whole site from Space Grotesk. It might be worth also asking the JetBrains people if they have any thoughts on that, and play around with a throwdown. Still, it's hard to beat the youthful, playful beauty of Space Grotesk when you look at it, for its fitness on this website.

Currently, I'm in favor of Input Mono. Though I think JetBrains Mono is about as good. I think either one is readable. I must defer to the two of you on this, since you seem to be regular contributors and I'm just a Processing teacher, albeit with experience in typography.

**Comment by SableRaf** [comment]
Input looks great but I think I still prefer JetBrains Mono. Hinting looks better at lower sizes/resolution in JetBrains Mono. It uses simpler glyphs for g, a, J and {} for example, and looks overall cleaner (subjectively). Ultimately, the license make the decision easy since Input is under a commercial license and JetBrains Mono is free and open source.

![image](https://github.com/processing/processing-website/assets/290261/e61c9947-e301-404f-a6ef-194366f82636)

**Comment by TechnicJelle** [comment]
I feel like there's a subtle but interesting difference also in the descriptions of the two.
Input is made for code, while JB Mono is made for developers.
This makes me think that while Input may _look_ better, JB Mono actually may _read_ better.
I hadn't noticed that before. Neat!

**Comment by pzelchenko** [comment]
Whoa, your image also shows JetBrains contrast is bumped up compared to Input. That's another advantage. Whatever the case, at a certain point things get a little transcendental and difficult to quantify. I think either one is a vast improvement. I suppose JetBrains is the consensus, then!

**Comment by SableRaf** [comment]
I've updated the code font to JetBrains Mono. Thanks @pzelchenko and @TechnicJelle for your input! Let me know if you notice any other issues.
