### ISSUE TITLE
Uneven Hover Effect on Navigation Bar

### ISSUE THREAD

**Issue by vishnuvardhnareddy** [processing/processing-website#551]
Issue:
In the navigation bar, menu items with submenus (classed as .item.hasSubmenu) do not display the same hover effect as those without submenus. Specifically, the buttons or links within these submenu items do not receive the hover styling applied to anchor tags, resulting in a visual inconsistency across the navigation bar.

![Screenshot 2024-08-12 202250](https://github.com/user-attachments/assets/f141370c-1792-4b1a-b855-b0df70b30d8c)
![Screenshot 2024-08-12 202303](https://github.com/user-attachments/assets/b91f73b3-be1a-4759-a5b5-ff9e7563d22b)

**Comment by SableRaf** [comment]
This issue is almost identical to issues https://github.com/processing/processing-website/issues/546 and https://github.com/processing/processing-website/issues/548 which have already been closed as "not planned".
