### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by SableRaf** [processing/processing-website#563]
The following links in the Processing website content have been found to be dead or inaccessible.

Each link listed below should be verified and either updated to a working URL or removed if no replacement is available.

## tutorials

- [ ] [404] http://www.learningprocessing.com/examples/chapter-17/example-17-8/ in ../content/tutorials/text/strings-and-drawing-text/index.mdx
- [ ] [404] http://www.designobserver.com/archives/007816.html. in ../content/tutorials/text/print/index.mdx
- [ ] [404] http://nettime.org/Lists-Archives/nettime-l-9703/msg00094.html. in ../content/tutorials/text/network/index.mdx
- [ ] [404] http://processing-website-user-testing.s3-website-us-east-1.amazonaws.com/download in ../content/tutorials/text/getting-started/index.es.mdx

## books

- [ ] [405] http://www.amazon.com/gp/product/0596514557?ie=UTF8&tag=processing09-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=0596514557 in ../content/books/visualizing-data/index.mdx
- [ ] [405] http://www.amazon.com/gp/product/1593276125/ref=as_li_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=1593276125&linkCode=as2&tag=processing09-20&linkId=B7WHOVIHDYFQDJQZ in ../content/books/sparkfun/index.mdx
- [ ] [405] http://www.amazon.com/gp/product/144931144X/ref=as_li_ss_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=144931144X&linkCode=as2&tag=processing09-20 in ../content/books/programming-interactivity/index.mdx
- [ ] [503] https://www.amazon.de/dp/3446477667 in ../content/books/programmieren-trainieren/index.mdx
- [ ] [404] http://www.lulu.com/content/8655305 in ../content/books/processing_andres_wanner/index.mdx
- [ ] [404] https://amzn.eu/d/cEPy36t in ../content/books/processing-lecode/index.mdx
- [ ] [404] https://amzn.eu/d/fYEZCC4 in ../content/books/processing-lecode/index.mdx
- [ ] [405] http://www.amazon.com/Processing-Programming-Handbook-Designers-Artists/dp/026202828X/ref=sr_1_6?s=books&ie=UTF8&qid=1406934187&sr=1-6&keywords=processing in ../content/books/processing-handbook/index.mdx
- [ ] [405] http://www.amazon.com/gp/product/1568817169?ie=UTF8&tag=processing09-20&linkCode=as2&camp=1789&creative=390957&creativeASIN=1568817169 in ../content/books/processing-for-visual-artists/index.mdx
- [ ] [405] http://www.amazon.com/gp/product/143024464X/ref=as_li_ss_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=143024464X&linkCode=as2&tag=processing09-20 in ../content/books/processing-creative-coding2/index.mdx
- [ ] [405] http://www.amazon.com/gp/product/159059617X?ie=UTF8&tag=processing09-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=159059617X in ../content/books/processing-creative-coding/index.mdx
- [ ] [null] http://www.friendsofed.com/book.html?isbn=159059617X in ../content/books/processing-creative-coding/index.mdx
- [ ] [405] https://www.amazon.com/Processing-Android-Create-Sensor-aware-Applications/dp/1484295846/ in ../content/books/processing-android-2/index.mdx
- [ ] [405] https://www.amazon.com/Processing-Android-Create-Sensor-aware-Applications/dp/1484295846/ in ../content/books/processing-android-2/index.es.mdx
- [ ] [405] https://www.amazon.com/Processing-Android-Create-Sensor-Aware-Applications/dp/1484227182 in ../content/books/processing-android/index.mdx
- [ ] [405] https://www.amazon.com/Processing-Introduction-Programming-Jeffrey-Nyhoff/dp/1482255952 in ../content/books/processing-an-introduction-to-programming/index.mdx
- [ ] [405] http://www.amazon.com/gp/product/0985930802/ref=as_li_ss_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=0985930802&linkCode=as2&tag=processing09-20 in ../content/books/nature-of-code/index.mdx
- [ ] [405] http://www.amazon.com/gp/product/0985930802/ref=as_li_ss_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=0985930802&linkCode=as2&tag=processing09-20 in ../content/books/nature-of-code/index.es.mdx
- [ ] [405] https://www.amazon.com/gp/product/0123944430/ref=as_li_ss_tl?ref_=nav_ya_signin&linkCode=sl1&tag=processing09-20&linkId=fb0eeedd8fb1016a790e83d538a1c030 in ../content/books/learning-processing-2/index.mdx
- [ ] [405] https://www.amazon.com/Learn-Python-Visually-Tristan-Bunn/dp/1718500963 in ../content/books/learn-python-visually/index.mdx
- [ ] [405] https://www.amazon.com/Learn-Python-Visually-Tristan-Bunn/dp/1718500963 in ../content/books/learn-python-visually/index.es.mdx
- [ ] [405] http://www.amazon.com/gp/product/1457187086/ref=as_li_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=1457187086&linkCode=as2&tag=processing09-20&linkId=JEJC22CTQ5ZF4ZYO in ../content/books/getting-started/index.mdx
- [ ] [405] http://www.amazon.com/gp/product/1616890770/ref=as_li_ss_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=1616890770&linkCode=as2&tag=processing09-20 in ../content/books/generative-design/index.mdx
- [ ] [405] http://www.amazon.com/gp/product/1935182625?ie=UTF8&tag=processing09-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=1935182625 in ../content/books/generative-art/index.mdx
- [ ] [403] http://www.lulu.com/shop/search.ep?keyWords=matthias+wolf&categoryId=100501 in ../content/books/einfuehrung-ins-programmieren-mit-processing/index.mdx
- [ ] [405] http://www.amazon.com/dp/1472578309/ in ../content/books/data-driven-graphic-design/index.mdx
- [ ] [405] http://amzn.to/2oS1Bx1 in ../content/books/creating-procedural-artworks/index.mdx
- [ ] [404] http://holistic3d.com/creating-procedural-artworks/ in ../content/books/creating-procedural-artworks/index.mdx
- [ ] [404] http://holistic3d.com/processing in ../content/books/creating-procedural-artworks/index.mdx
- [ ] [405] https://www.amazon.nl/Coding-Art-Unlocking-Creativity-Processing/dp/1484297792 in ../content/books/coding-art-jp/index.es.mdx
- [ ] [503] https://www.amazon.nl/Coding-Art-Unlocking-Creativity-Processing/dp/1484297792 in ../content/books/coding-art-2/index.mdx
- [ ] [503] https://www.amazon.nl/Coding-Art-Unlocking-Creativity-Processing/dp/1484297792 in ../content/books/coding-art-2/index.es.mdx
- [ ] [405] https://www.amazon.com/gp/product/1484262638 in ../content/books/coding-art/index.mdx
- [ ] [405] https://www.amazon.com/gp/product/1484262638 in ../content/books/coding-art/index.es.mdx
- [ ] [404] http://www.bnn.co.jp/books/title_index/web/processing.html in ../content/books/built-with-processing/index.mdx
- [ ] [404] http://www.bnn.co.jp/books/title_index/web/processing.html in ../content/books/built-with-processing/index.es.mdx
- [ ] [405] http://www.amazon.com/gp/product/0470375485?ie=UTF8&tag=processing09-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=0470375485 in ../content/books/algorithms-for-visual-design/index.mdx
- [ ] [405] http://www.amazon.com/gp/product/0470375485?ie=UTF8&tag=processing09-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=0470375485 in ../content/books/algorithms-for-visual-design/index.es.mdx

## contributions

- [ ] [404] https://tramontana.xyz/tramontanacv in ../content/contributions/tramontanaCV.json
- [ ] [404] http://igeo.jp/igeo.zip in ../content/contributions/iGeo.json
- [ ] [405] https://arcane.info/ in ../content/contributions/extruder.json
- [ ] [405] http://kiml.org/WootingKeyboard in ../content/contributions/WootingKeyboard.json
- [ ] [405] http://kiml.org/WootingKeyboard in ../content/contributions/WootingKeyboard.json
- [ ] [null] https://www.wooting.nl/ in ../content/contributions/WootingKeyboard.json
- [ ] [null] https://www.wooting.nl/ in ../content/contributions/WootingKeyboard.json
- [ ] [404] http://web.media.mit.edu/~mellis/ in ../content/contributions/WOVNS_Examples.json
- [ ] [null] http://www.wovns.com/tutorials/designing-computational-textiles-with-processing/ in ../content/contributions/WOVNS_Examples.json
- [ ] [null] https://www.smallbutdigital.com/ in ../content/contributions/The_MidiBus.json
- [ ] [null] https://www.smallbutdigital.com/themidibus.php in ../content/contributions/The_MidiBus.json
- [ ] [500] http://interfaze.info/libraries/tablet/ in ../content/contributions/Tablet.json
- [ ] [404] http://www.lagers.org.uk/s4p/applets/s4p_showcase in ../content/contributions/Sprites.json
- [ ] [404] http://nok.onl in ../content/contributions/SoundCloud.json
- [ ] [404] https://github.com/soundcloud/java-api-wrapper in ../content/contributions/SoundCloud.json
- [ ] [null] http://www.hamzeen.com in ../content/contributions/ShortMessage.json
- [ ] [null] https://www.izzatariq.com/ in ../content/contributions/Shader_Mode.json
- [ ] [404] https://www.github.com/ReferenceTool in ../content/contributions/Reference_Tool.json
- [ ] [404] http://nok.onl in ../content/contributions/Redis.json
- [ ] [403] https://twitter.com/jrc03c in ../content/contributions/QueasyCam.json
- [ ] [null] http://sphaero.org in ../content/contributions/ProcMod_player.json
- [ ] [null] http://www.thomaswegener.ch in ../content/contributions/OCT.json
- [ ] [404] http://nok.onl in ../content/contributions/Myo_for_Processing.json
- [ ] [null] https://www.thalmic.com in ../content/contributions/Myo_for_Processing.json
- [ ] [null] https://www.thalmic.com in ../content/contributions/Myo_for_Processing.json
- [ ] [404] http://www.mukprojects.at in ../content/contributions/MuKCast.json
- [ ] [404] http://nok.onl in ../content/contributions/Leap_Motion_for_Processing.json
- [ ] [404] http://StaticVoidGames.com/JarMatey/ in ../content/contributions/JarMatey.json
- [ ] [null] http://www.hirschandmann.com in ../content/contributions/Image_Sequence_Player.json
- [ ] [404] http://www.mukprojects.at in ../content/contributions/ImageLoader.json
- [ ] [403] http://ciaron.net in ../content/contributions/HPGLGraphics.json
- [ ] [500] http://www.extrapixel.ch in ../content/contributions/GifAnimation.json
- [ ] [null] http://bpolonski.com in ../content/contributions/Free_Transform.json
- [ ] [404] http://code.andreaskoller.com/libraries/fontastic in ../content/contributions/Fontastic.json
- [ ] [null] http://pphys2d.jmcouillard.com/ in ../content/contributions/Fisica.json
- [ ] [null] https://theeyetribe.com/ in ../content/contributions/Eye_Tribe_for_Processing.json
- [ ] [500] http://interfaze.info/ in ../content/contributions/Eliza.json
- [ ] [500] http://interfaze.info/libraries/eliza/ in ../content/contributions/Eliza.json
- [ ] [405] http://www.jaysonh.com in ../content/contributions/DMX4Artists.json
- [ ] [null] http://dhchoi.com in ../content/contributions/CountdownTimer.json
- [ ] [404] http://www.mukprojects.at in ../content/contributions/Console.json
- [ ] [404] https://github.com/jashkenas/coffee-script]. in ../content/contributions/CoffeeScript_Mode.json
- [ ] [405] https://dringtech.com/ in ../content/contributions/Coding_Creative.json
- [ ] [null] http://benitomedia.com in ../content/contributions/Beads.json
- [ ] [404] http://www.lagers.org.uk/appletutil/ in ../content/contributions/Applet_Maker_&_Signer.json
- [ ] [404] http://nok.onl in ../content/contributions/$1_Unistroke_Recognizer.json

## other

- [ ] [404] https://github.com/processing/processing-contributions in ../docs/libraries.md
- [ ] [404] http://processing-website-user-testing.s3-website-us-east-1.amazonaws.com/books in ../docs/books.md

# Original list from script

[dead_links.json](https://github.com/user-attachments/files/17244656/dead_links.json)

**Comment by rishabdev2997** [comment]
Hi @SableRaf 
Could you elaborate on what steps you’d like me to take for this? I’m interested in working on it.

**Comment by SableRaf** [comment]
Thanks for your interest in taking on this issue @rishabdev2997! Just a heads-up—this is a pretty big task, and I don’t expect one person to solve the whole thing. But you can definitely make progress by going through the list of dead links and finding alternatives that are working.

The book section has some low-hanging fruit, like the Amazon links, which should be relatively easy to fix. For any others that don’t have obvious replacements, we'll have to handle them case by case.

FYI: I generated the list using [this script](https://github.com/processing/processing-website/blob/dead-links-script/scripts/checkDeadLinks.js) and turned it into a list of todos with [this script](https://github.com/processing/processing-website/blob/dead-links-script/scripts/deadLinksTodos.js) which live on a separate branch for now.

Feel free to reach out if you have any questions along the way!

**Comment by twisst** [comment]
Note: it seems like this list is external dead links only. In 
https://processing.org/tutorials/text I encountered this internal dead link:
https://processing.org/learning/trig/
(And yes, I will fix this one in a PR that I will do for the other thing :-))

**Comment by SableRaf** [comment]
@twisst You're right, the list above was made by looking at external links only. I made the following two scripts for it: [checkDeadLinks.js](https://github.com/processing/processing-website/blob/dead-links-script/scripts/checkDeadLinks.js) to generate the list and [deadLinksTodos.js](https://github.com/processing/processing-website/blob/dead-links-script/scripts/deadLinksTodos.js) to format it in MarkDown. These scripts are living on a separate branch right now.
