### ISSUE TITLE
Hand cursor not showing for clickable elements

### ISSUE THREAD

**Issue by SableRaf** [processing/processing-website#587]
### Describe the bug

The hand cursor (used to indicate clickable links) briefly appears when hovering over clickable elements but instantly reverts to an arrow cursor. This affects all clickable items on the website, including text, cards, buttons, and menus.

### Expected behavior

The hand cursor should consistently display when hovering over links to indicate they are clickable.

### Screenshots

https://github.com/user-attachments/assets/05e154dd-ee08-4df2-95ec-71c62c483ce6

### Browser

Firefox, Chrome, Safari

### Operating system

macOS 13.4 (22F66)

**Comment by Stefterv** [comment]
https://github.com/user-attachments/assets/9993e8a0-7d4b-43d3-b388-990bebdbdd29

I see the same thing, but only when I'm screen recording 👀

**Comment by SableRaf** [comment]
The issue was happening before I started recording, but it has disapeared after a reboot so there must have been something wrong with my session. All good!
