### ISSUE TITLE
Contribution Feedback

### ISSUE THREAD

**Issue by ejsandoval** [processing/processing-website#74]
Here's a list of features/issues coming from the volunteers who help us with the content update:

- [x] Syntax Highlighting with `highlight.js`
- [x] Fix CSS on the Reference's examples: with 2 images the same size (800x800), one appears bigger than the other.
- [x] Order of the examples in the index can be curated and not default to alphabetical order.
- [x] Examples json description with some source code in comments as well as multi-line descriptions 
- [x] Add MDX component to have images in a horizontal row, with the text (code) underneath
- [x] Images in MDX with wrong paths on Windows
- [ ] The Description text often refers directly to the Parameters. With the new layout, they are separated on the page by the Examples. Review the relationship between the two.

**Comment by runemadsen** [comment]
Closing in favor of #92
