### ISSUE TITLE
Adding Weight Line Example to processing 

### ISSUE THREAD

**Issue by SanjaySinghRajpoot** [processing/processing-website#79]
Actual Behaviour

Weight Line Example is missing from processing 

Expected Behaviour

Adding Weight Line Example from p5.js to processing 

Screenshots of the issue
![image](https://user-images.githubusercontent.com/67458417/112718880-db3c8e80-8f1b-11eb-9116-7a02fdc636f8.png)

Yes, I would like to work on this issue.

**Comment by runemadsen** [comment]
Hi @SanjaySinghRajpoot. Thanks for this! If you would like to add this example to the Processing website, feel free to send a PR for it. You can read more about how to add examples [in this file](https://github.com/processing/processing-website/blob/master/docs/examples.md).

**Comment by runemadsen** [comment]
Closing this. Feel free to submit a PR if you get a chance to do it!
